apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfirstproject
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: myfirstproject
  template:
    metadata:
      labels:
        app: myfirstproject
    spec:
      containers:
        - image: my-first-project:latest
          name: myfirstproject
          imagePullPolicy: Never
          ports:
            - containerPort: 80